### ISSUE TITLE
make allでImport Errorが発生する

### ISSUE THREAD

**Issue by KUrushi** [hottolink/pydams#2]
pydams/pydamsにlibdams-4.3.4.soをコピーしても以下のようなエラーが出ます
ImportError: libdams-4.3.4.so: cannot open shared object file: No such file or directory

インストール手順について、もう少し詳細なものが知りたいです

**Comment by s-mizuki** [comment]
@KUrushi 
ご報告ありがとうございます．
反応が遅れましたこと，ご容赦ください．

ご質問の点は，共有ライブラリが認識されていないことが原因と推察します．

このpackageは，damsの共有ライブラリ(=`libdams-4.3.4.so`)がシステムにインストール済みであることを前提としています．
ついては，インストール方法が明確になるように，READMEを追記いたしました．
READMEに記載のインストール手順にしたがって，あらためてインストールを試みていただけると幸いです．
