### ISSUE TITLE
パッチ適用後に「福島県大沼郡金山町越川五十苅象」の座標を求めるとエラーとなる

### ISSUE THREAD

**Issue by mima3** [hottolink/pydams#5]
パッチを適用すると「福島県大沼郡金山町越川五十苅象」、「新潟県新潟市西区五十嵐中島」のような町名に２桁の漢数字を含む住所の座標を求めるとエラーになります。

## 手順
1. パッチを適用してビルドを行う  
2. 下記のコマンドを実行する

```
src/dams 福島県大沼郡金山町越川五十苅象
```

## 期待
パッチ適用前と同じ結果を返す

## 実際
下記のエラーが出力される。

```
Unexpected return value detected from nconverted, match length is negative value when processing
```

## 備考
下記のパッチの修正箇所を元に戻すと当該事象は発生しなくなる。

```patch
-    if (result.maxlen < 0) {
+    if (result.maxlen < 0 || result.maxlen - abs(matchlen) < 0) {
```

**Comment by s-mizuki** [comment]
ご報告ありがとうございます．現象を確認しました．
解決方法を模索中につき，しばらくお待ちください．

この問題は相応に根深いところがあり，修正を元に戻すだけでは #4 が再発します．
一方で，ご指摘の事例以外にも，漢数字+ヶを含む住所（例：`青森県上北郡六ヶ所村`）もエラーになることを確認しました．
影響範囲が思いの外に大きいため，Degradeを避けつつ何らかの解決策を講じるつもりです．

**Comment by s-mizuki** [comment]
@mima3 
対応いたしました．こちらでいかがでしょうか．
ce5129e6b4de6753b1f1f0533df6d5fea60f3d3a

**Comment by mima3** [comment]
対応ありがとうございました。
オリジナルのdamsのコードに対して[パッチ](https://github.com/hottolink/pydams/blob/bugfix/patch/dams-4.3.4.diff)にあてることにより
報告済みの住所と「東京都足立区/バイク/スポーツ/仲間集め」の座標が取得できることが確認できました。

**Comment by s-mizuki** [comment]
対応できている旨，了解しました．
なおテストコードも若干修正いたしました．

これでcloseいたします．
ご利用およびご報告，たいへんありがとうございました．感謝申し上げます．
